<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>SamplePlugin</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Viora.Core\Viora.Core.csproj" />
    <ProjectReference Include="..\..\src\Viora.PluginSdk\Viora.PluginSdk.csproj" />
  </ItemGroup>

</Project>
